import Head from 'next/head';

import { Footer, ResponsiveAppBar } from '@/components';
import { GroceriesCardsList } from '@/features/grocery-item';
import styles from '@/styles/Home.module.css';

const groceries = [
    { name: 'תפוח', price: 1.99, id: '' },
    { name: 'ענבים', price: 2.99, id: '' },
    { name: 'קוקה קולה', price: 3.99, id: '' },
    { name: 'מיץ תפוזים', price: 5.99, id: '' },
    { name: 'אוריאו', price: 9.99, id: '' },
    { name: 'עוף', price: 6.99, id: '' },
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ResponsiveAppBar />

            <main className={styles.main}>
                <GroceriesCardsList groceries={groceries} />
            </main>

            <Footer />
        </>
    );
}
